# Generated by Django 3.1 on 2020-08-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='slug',
            field=models.SlugField(default='0000000', max_length=200, unique=True),
        ),
    ]
