# Generated by Django 3.1 on 2020-08-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200814_0158'),
        ('info', '0003_auto_20200814_0727'),
    ]

    operations = [
    ]
