# Generated by Django 3.1 on 2020-08-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_merge_20200814_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
